apiVersion: apps/v1
kind: Deployment

metadata:
  name: student-deployment
  labels:
    app: studentportal
    env: test

spec:
  replicas: 4
  minReadySeconds: 30

  selector:
    matchLabels:
      app: studentportal

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%

  template:
    metadata:
      labels:
        app: studentportal

    spec:
      containers:
        - name: student-con
          image: aravindh146/studentportal:v2

          ports:
            - containerPort: 8080

          env:
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: studentportal-secret
                  key: ConnectionStrings__DefaultConnection

          volumeMounts:
            - name: secrets-store
              mountPath: "/mnt/secrets"
              readOnly: true

          resources:
            requests:
              cpu: "500m"
              memory: "500Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"

          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
            initialDelaySeconds: 35
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 10

      volumes:
        - name: secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: mysql-secrets