apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass

metadata:
  name: mysql-secrets

spec:
  provider: azure

  secretObjects:
    - secretName: studentportal-secret
      type: Opaque
      data:
        - objectName: mysql-connection-string
          key: ConnectionStrings__DefaultConnection

  parameters:
    clientID: "2410506f-537d-48c8-9f20-9f39859262b0"

    keyvaultName: "kv-dev-aks-demo"

    tenantId: "e6a3c47f-e8fa-445d-bd4d-af055614fbcb"

    objects: |
      array:
        - |
          objectName: mysql-connection-string
          objectType: secret