apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.secrets.secretName}}
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: {{.Values.secrets.stringData.ConnectionStrings__DefaultConnection}}
  
  